name: CVBuilder CI/CD Pipeline With Gradle, Docker & SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'gradle'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x gradlew

      - name: Build application with Gradle (без тестов)
        run: ./gradlew build -x test --no-daemon

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: cvbuilder-backend-jar
          path: build/libs/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t cvbuilder-backend:latest .

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Wait for Database to be Ready
        run: sleep 10

      - name: List Running Containers (Debug)
        run: docker ps -a

      - name: Stop and Remove Containers
        run: docker-compose down
